from enum import Enum

# SOURCE_INPUT_FILES = [
#   ("UrinaryIncontinence.csv", "https://drive.google.com/uc?id=1CQXJvSpA7KVeGImypLSBPerPlzd-7Osp"),
#   ("Hall_2012.csv", "https://drive.google.com/uc?id=1HUc4UxTQ3_4SaPz2FvXUkuB49Y5YNB1p"),
#   ("ProtonPumpInhibitors.csv", "https://drive.google.com/uc?id=1t8MsIwLdjF3LsrFRjy00tvU52gVsG4ld"),
#   ("van_de_Schoot_2017.csv", "https://drive.google.com/uc?id=1BFQTrOg-FjTK5gtw-1pUBpqFvrLRJoij"),
#   ("SkeletalMuscleRelaxants.csv", "https://drive.google.com/uc?id=1LXOdKDGWG7ZE_nsGJFn0VfKOkp-3yuBu"),
#   ("Kwok_2020.csv", "https://drive.google.com/uc?id=1cnZoP28syi7N9bLeerk8f234C4E53KqE"),
#   ("Nagtegaal_2019.csv", "https://drive.google.com/uc?id=1P5hMvAiYomEwp2TY9TPOb2B8Ih9dX6Qc"),
#   ("Wolters_2018.csv", "https://drive.google.com/uc?id=1f75DjbnWYiJJAumzOWNCFTd9oLZjb68S"),
#   ("Kitchenham_2010.csv", "https://drive.google.com/uc?id=1A5Y1Nu3udcsqHUN6jOeVBKXjtSeyaQVb"),
#   ("Radjenovic_2013.csv", "https://drive.google.com/uc?id=14J4yjyjy0u4rvNyRZ7nUxOPWU0dtUm86"),
#   ("Triptans.csv", "https://drive.google.com/uc?id=1wDQzkzP4z6p8IT5egxszJZQmtuHJ-MJD"),
#   ("Wahono_2015.csv", "https://drive.google.com/uc?id=1t72QNc3_miWsS_ht2Kxc40PnE9Lp9ZqC"),
#   ("Statins.csv", "https://drive.google.com/uc?id=1mLg5o9M1HDcjyOpZUXxs2EF0OWvDuov-"),
#   ("van_Dis_2020.csv", "https://drive.google.com/uc?id=1JTCX0gQ2KIwnKfud_7LOV11NkaqzmJHo"),
#   ("ADHD.csv", "https://drive.google.com/uc?id=1FMGWV80MI1Pq8_a_GuIxO_5xZrw71ajm"),
#   ("ACEInhibitors.csv", "https://drive.google.com/uc?id=1X7S4JT7wx-D7vxwmgBRWowyZ-PJoDmkv"),
#   ("Opiods.csv", "https://drive.google.com/uc?id=1xf-HecsXREPHwFr-dClt3nk2G7yqyxms"),
#   ("AtypicalAntipsychotics.csv", "https://drive.google.com/uc?id=1qgguRWxDqqEk3Go3wahopei0RSvMkt6q"),
#   ("CalciumChannelBlockers.csv", "https://drive.google.com/uc?id=1EmT3H3emE9KlCAaYkMEd-F71vgQbBy0q"),
#   ("BetaBlockers.csv", "https://drive.google.com/uc?id=1h7gRtBf6YqIlwu4dYVCNbZgQWl3s7Zvm"),
#   ("NSAIDS.csv", "https://drive.google.com/uc?id=137mglPeSXUr5wVkzO3QmzKWVsgz0B9Iq"),
#   ("Bannach-Brown_2019.csv", "https://drive.google.com/uc?id=1Xid0OTXSycHRTR7CzpZ2BYjScBrttPQS"),
#   ("Appenzeller-Herzog_2020.csv", "https://drive.google.com/uc?id=1sPxDAQtmfB3nOjeJWwsyLxcFQrbYs3R3"),
#   ("OralHypoglycemics.csv", "https://drive.google.com/uc?id=188Yb5svRlphVuVwUudKWq3TsryWdJ2Cp"),
#   ("Antihistamines.csv", "https://drive.google.com/uc?id=1FSa6URUSiqbzuDq6cwVOK5IwdCauQkXF"),
#   ("Bos_2018.csv", "https://drive.google.com/uc?id=1H5yBNB_BtuHtxgcDLI7q1YfMiGwAxu-I"),
#   ("Estrogens.csv", "https://drive.google.com/uc?id=1ASCDXZ1yP0GTaQYdbBvWRxmFdXNw-O1f"),
# ]

SOURCE_INPUT_FILES = [
  ("UrinaryIncontinence.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Cohen_2006/output/local/UrinaryIncontinence.csv"),
  ("Hall_2012.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Hall_Wahono_Radjenovic_Kitchenham/output/Hall_2012.csv"),
  ("ProtonPumpInhibitors.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Cohen_2006/output/local/ProtonPumpInhibitors.csv"),
  ("van_de_Schoot_2017.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/van_de_Schoot_2017/output/van_de_Schoot_2017.csv"),
  ("SkeletalMuscleRelaxants.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Cohen_2006/output/local/SkeletalMuscleRelaxants.csv"),
  ("Kwok_2020.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Kwok_2020/output/Kwok_2020.csv"),
  ("Nagtegaal_2019.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Nagtegaal_2019/output/Nagtegaal_2019.csv"),
  ("Wolters_2018.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Wolters_2018/output/Wolters_2018.csv"),
  ("Kitchenham_2010.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Hall_Wahono_Radjenovic_Kitchenham/output/Kitchenham_2010.csv"),
  ("Radjenovic_2013.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Hall_Wahono_Radjenovic_Kitchenham/output/Radjenovic_2013.csv"),
  ("Triptans.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Cohen_2006/output/local/Triptans.csv"),
  ("Wahono_2015.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Hall_Wahono_Radjenovic_Kitchenham/output/Wahono_2015.csv"),
  ("Statins.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Cohen_2006/output/local/Statins.csv"),
  ("van_Dis_2020.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/van_Dis_2020/output/van_Dis_2020.csv"),
  ("ADHD.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Cohen_2006/output/local/ADHD.csv"),
  ("ACEInhibitors.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Cohen_2006/output/local/ACEInhibitors.csv"),
  ("Opiods.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Cohen_2006/output/local/Opiods.csv"),
  ("AtypicalAntipsychotics.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Cohen_2006/output/local/AtypicalAntipsychotics.csv"),
  ("CalciumChannelBlockers.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Cohen_2006/output/local/CalciumChannelBlockers.csv"),
  ("BetaBlockers.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Cohen_2006/output/local/BetaBlockers.csv"),
  ("NSAIDS.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Cohen_2006/output/local/NSAIDS.csv"),
  ("Bannach-Brown_2019.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Bannach-Brown_2019/output/Bannach-Brown_2019.csv"),
  ("Appenzeller-Herzog_2020.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Appenzeller-Herzog_2020/output/Appenzeller-Herzog_2020.csv"),
  ("OralHypoglycemics.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Cohen_2006/output/local/OralHypoglycemics.csv"),
  ("Antihistamines.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Cohen_2006/output/local/Antihistamines.csv"),
  ("Bos_2018.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Bos_2018/output/Bos_2018.csv"),
  ("Estrogens.csv", "/Users/matheusmota/src/github/msc/systematic-review-datasets/datasets/Cohen_2006/output/local/Estrogens.csv"),
]
class WorflowTaskQueue(Enum):
  ML_TASK_QUEUE = "ml-task-queue"
